server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.163.128:3306/SecKill
    username: root
    password: SSYVcal262
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.163.128
    port: 6379

